### ISSUE TITLE
How can we extend this?

### ISSUE THREAD

**Issue by 0xlabz** [dicebear/dicebear#102]
Is there any way for us to extend this and generate avatars with our own art? If yes, Is there a documentation we can refer to? Thanks!

**Comment by FlorianKoerner** [comment]
Currently there is no documentation describing how to add avatar styles yourself. But it is not that difficult.

You just have to write a function ([Example](https://github.com/dicebear/dicebear/blob/v4/packages/avatars-initials-sprites/src/index.ts#L19)) that expects two parameters.  With the first parameter you get the [PRNG](https://github.com/dicebear/dicebear/blob/v4/packages/avatars/src/random.ts) and with the second parameter the options. The function can then generate the avatar and return it in SVG format. What exactly happens in the function is up to you.

**Comment by 0xlabz** [comment]
I'm looking into it now. Thanks! Is there a way to print all the attributes used in a JSON format? For example:
```js
{
  hairColor: brown,
  eyes: blue,
  top: shirt,
  ...
}
```

Been looking at it but can't figure out how the seed is feed into Random generator to get the output attributes.

I'm assuming it's [here](https://github.com/dicebear/dicebear/blob/v4/packages/avatars/src/index.ts#L61) but would be helpful if you can point me in the right direction. Thanks!

**Comment by FlorianKoerner** [comment]
I don't quite understand your question. Do you have Discord? Maybe we can look at your problem there.
https://discord.gg/tghwpewr45

Whenever you need a random value you have to call an PRNG method.

For example, to have a value selected from an array:

```ts
export default function (prng, options = {}) {
    let values = ['A', 'B', 'C'];
    let firstRandomValue = prng.pickone(values);
    let secondRandomValue = prng.pickone(values);

   console.log(firstRandomValue, secondRandomValue);

    return '<svg></svg>';
}
```

Result of `firstRandomValue` and `secondRandomValue` will depend on your seed.
