### ISSUE TITLE
[Q&A] How to Host avataaars on our servers

### ISSUE THREAD

**Issue by theMasix** [dicebear/dicebear#103]
Hello.
Due to poor stability of official CDN, we've decided to host specific part of this project on our servers. So we wanna use avataaars section and host it on our servers.
We just wanna know how we can use it and deploy it?
At the end, we want to have access to avataaars using links, like what we already have on official CDN

**Comment by FlorianKoerner** [comment]
We are not aware of any stability problems at the moment. Would you like to go into a little more detail so that we can solve the problem in your region?

https://dicebear.betteruptime.com/

Regarding your question, there are two ways to run the API yourself.

Using a NodeJS server:
https://github.com/dicebear/api

Or serverless with Cloudflare Workers:
https://avatars.dicebear.com/integrations/serverless

**Comment by theMasix** [comment]
Thanks for instant response and useful links.
I'll give you some details about API accessibility problems.

But for now, can we deploy this Avatars package using serverless functions on Vercel or Netlify? (As we're working with them right now)

**Comment by theMasix** [comment]
But About API response issues, after conversation at #89 , you introduces [New API versioning](after https://github.com/dicebear/dicebear/issues/89#issuecomment-739424766), so we decided to use version `4.5` and we taught "Yeah, we no more have Dicebear API issue!". but since 2weeks ago, our requests was responded by JSON not SVG. like this:
![image](https://user-images.githubusercontent.com/22872117/111308956-90e02580-8670-11eb-8cdd-879259e90d3b.png)

I don't know why this issue is raised(since there is no breaking changes in changelog) and we now decide to host this API on our servers and not to use official CDN.

I hope you can have more stable API system and no one like us, will force to do what we decide to do!

**Comment by FlorianKoerner** [comment]
Thanks for describing the problem. We recently changed our validator library. When we made the change, we mistakenly defined "clothes" as "string". I have just corrected the error.

Currently there is no official support for Vercel and/or Netlify. But you can of course write your own implementation. That might help:

- https://avatars.dicebear.com/styles/avataaars#npm
- https://github.com/dicebear/serverless/blob/main/src/actions/avatar.ts
- https://docs.netlify.com/functions/build-with-javascript/
- https://vercel.com/docs/serverless-functions/introduction
