### ISSUE TITLE
Download the avatar

### ISSUE THREAD

**Issue by Hamzajoshan** [dicebear/dicebear#105]
How i can download the Avatar ?

**Comment by FlorianKoerner** [comment]
Just click on it and save the image to your computer.

<img width="496" alt="Bildschirmfoto 2021-04-07 um 22 05 44" src="https://user-images.githubusercontent.com/647303/113927161-67d52f80-97ed-11eb-928f-fe34a29dbba0.png">

https://avatars.dicebear.com/api/male/.svg
