### ISSUE TITLE
HTTP-API 404

### ISSUE THREAD

**Issue by tomascsantos** [dicebear/dicebear#124]
Hi there, I've been using your cool tool for a month or so. I just found that the HTTP-API doesn't seem to be working for me anymore. for example this url:
`https://avatars.dicebear.com/api/:sprites/:seed.svg`
copied directly from the website example: https://avatars.dicebear.com/docs/http-api
gives me a 
`{"message":"Route GET:/api/:sprites/:seed.svg not found","error":"Not Found","statusCode":404}`

Am I doing something incorrectly? Thanks for the help!

**Comment by FlorianKoerner** [comment]
The solution is directly below the example url:

> Replace :sprites with `male`, `female`, `human`, `identicon`, `initials`, `bottts`, `avataaars`, `jdenticon`, `gridy` or `micah`.  The value of `:seed` can be anything you like - but don't use any sensitive or personal data here!

**Comment by tomascsantos** [comment]
Ok that was a silly mistake. Thank you for your time. 

I'm still experiencing issues though. Previously your endpoint allowed me to request png files. Now only svg seem to be available. I'm having a really tough time using it now because I can't seem to render SVG icons in my react native application. This is my rendering code:
```
import {SvgCssUri} from "react-native-svg";      
<Avatar rounded size="medium">
    <SvgCssUri width="100%" height="100%" uri={url} />
</Avatar>
```

however I keep getting an error: 
`Text strings must be rendered within a <Text> component`

Any help would be really appreciated I loved using your library in the past and want to keep using it but I just can't get it to work right now.
Thanks!!

**Comment by FlorianKoerner** [comment]
Yes, PNG support was discontinued after a test period of 2 months.

In #87 a solution for React Native was discussed. Maybe it will help you too.

**Comment by tomascsantos** [comment]
After additional testing, I've found that only the bottts endpoint generates this error. I'm not sure what makes it different but I'll just use another style for now.

**Comment by FlorianKoerner** [comment]
Are you passing any options in the parameters? If you pass invalid options, the API returns a text error and not an SVG. This could explain your error. Bottts work fine in my tests.
