### ISSUE TITLE
@dicebear/micah the dougFunny hair style is always black

### ISSUE THREAD

**Issue by WilliamRADFunk** [dicebear/dicebear#131]
![image](https://user-images.githubusercontent.com/10148684/123024453-eb82cf00-d38d-11eb-9cb4-719be042c7e9.png)

![image](https://user-images.githubusercontent.com/10148684/123024474-f3db0a00-d38d-11eb-8acb-f7b6b1612e94.png)

`return createAvatar(
            style,
            {
                backgroundColor: '#555',
                seed: 'john-does-freedman',
                eyes: ['round'],
                eyebrows: ['up'],
                eyebrowColor: ['white'],
                facialHairColor: ['white'],
                facialHairProbability: 100,
                glassesProbability: 0,
                hair: ['dougFunny'],
                hairColor: ['white'],
                mouth: ['smile']
            });`

I've tried to force other hair colors, but the result is always black for this one hair style.

**Comment by FlorianKoerner** [comment]
Fixed. https://github.com/dicebear/dicebear/releases/tag/v4.6.6

<img width="300" alt="Bildschirmfoto 2021-06-23 um 07 39 14" src="https://user-images.githubusercontent.com/647303/123041788-1e60ad80-d3f6-11eb-8317-0cefcff7a7b4.png">

**Comment by WilliamRADFunk** [comment]
Awesome!
