### ISSUE TITLE
Black lip lines lost in lack of contrast against black beards

### ISSUE THREAD

**Issue by WilliamRADFunk** [dicebear/dicebear#132]
![image](https://user-images.githubusercontent.com/10148684/123156992-d7d37900-d41e-11eb-9641-872944044b19.png)

Not exactly a bug, per se. Just that since all the lips are drawn in black, they are completely lost against a black beard.

I guess it can pass as a black COVID mask in these days :p

**Comment by FlorianKoerner** [comment]
COVID mask 😄 

Fixed with 4.6.9
https://github.com/dicebear/dicebear/releases/tag/v4.6.9

<img width="300" alt="Bildschirmfoto 2021-06-23 um 23 06 05" src="https://user-images.githubusercontent.com/647303/123167955-99b67380-d477-11eb-9e06-029c1f7a74f7.png">

**Comment by WilliamRADFunk** [comment]
Excellent. Thanks!
