### ISSUE TITLE
Avataaars clotheGraphics doesn't work

### ISSUE THREAD

**Issue by galvarez421** [dicebear/dicebear#135]
Hello, first off, thank you for this wonderful library!

I am trying to use the avataaars style and the `clotheGraphics` style option doesn't seem to work, unless I'm just missing something! For example, see https://avatars.dicebear.com/api/avataaars/test.svg?clothes=graphicShirt&clotheGraphics=skullOutline. I am actually using the npm package but that URL shows the same issue I am experiencing using the npm package.

**Comment by FlorianKoerner** [comment]
Hello galvarez421. Thank you for your bug report. The bug has been fixed with version 4.6.10.

**Comment by galvarez421** [comment]
Awesome, thank you!
