### ISSUE TITLE
List of sprite categories seems to not be up to date (?)

### ISSUE THREAD

**Issue by mousetail** [dicebear/dicebear#231]
On this page there is a list of possible categories for sprites: https://avatars.dicebear.com/docs/http-api

However, this list seems to be missing a lot of sprites while including categories that other parts of the docs say are deprecated. I want to generate sprites from a random set so it would be helpful to have a actual list of options for the API there.

**Comment by FlorianKoerner** [comment]
Hi @mousetail 

Yes, the list on the page is a bit outdated. I am currently working on updated documentation.

You can use the following avatar styles (sprites):

- adventurer
- adventurer-neutral
- avataaars
- big-ears
- big-ears-neutral
- big-smile
- bottts
- croodles
- croodles-neutral
- identicon
- initials
- micah
- miniavs
- open-peeps
- personas
- pixel-art
- pixel-art-neutral

**Comment by FlorianKoerner** [comment]
I have fixed it on the website.
