### ISSUE TITLE
TypeScript 4.8 incompatibility

### ISSUE THREAD

**Issue by dhess** [dicebear/dicebear#239]
Hi, thanks for this package!

TypeScript 4.8's strict null checks break at least some of the types in the `avatars` package:

```
../../node_modules/.pnpm/@dicebear+avatars@4.10.3/node_modules/@dicebear/avatars/dist/types.d.ts(46,27): error TS2344: Type 'O' does not satisfy the constraint '{}'.
```

**Comment by FlorianKoerner** [comment]
Hi @dhess 

Can you provide me with a minimal sample project? Then I can reproduce the error more easily.
