### ISSUE TITLE
Identicon API returning 502 errors

### ISSUE THREAD

**Issue by dcporter44** [dicebear/dicebear#243]
Hi there!

I've been using your API for a while now, it's been great. I'm specifically using this API: https://avatars.dicebear.com/styles/identicon

I'm using the HTTP-API method like so: https://avatars.dicebear.com/api/identicon/:seed.svg

However, I'm just noticing this is returning 502 errors. Sometimes it works after a long response time. I'm not sure how long this has been going on, I just noticed today.

If this is a temporary server issue, I'd appreciate any updates. Thanks!

**Comment by dcporter44** [comment]
<img width="1440" alt="Screen Shot 2022-10-19 at 12 28 05 PM" src="https://user-images.githubusercontent.com/13480498/196785600-24be43e8-25a9-4660-9a02-55822f85e3df.png">

Here's what it looks like in the browser.

If it's a previously accessed :seed, then your server seems to be caching it and responds really quickly. But any uncached seeds are having this issue.

**Comment by FlorianKoerner** [comment]
Hi @dcporter44

Thank you for your hint. Someone was making thousands of requests to the API every second. I have set a rate limit.

**Comment by dcporter44** [comment]
You're awesome, thanks!
