### ISSUE TITLE
confusion in the sexes (genders)

### ISSUE THREAD

**Issue by Neakit** [dicebear/dicebear#247]
[an unknown being](https://skr.sh/sH2YfR99O2v?a)

**Comment by FlorianKoerner** [comment]
The generated avatars are to be understood gender-free in the first moment. You can use the options to define which hair, clothes and colors speak for you for one or the other gender.

- https://github.com/dicebear/dicebear/issues/21
- https://github.com/dicebear/dicebear/issues/180
- https://github.com/dicebear/dicebear/discussions/148
