### ISSUE TITLE
Links to Adventurer source and author do not work

### ISSUE THREAD

**Issue by GrahamLea** [dicebear/dicebear#250]
Both of the first two links on this page, which are trying to give attribution to the designer, are broken/stale: https://avatars.dicebear.com/styles/adventurer

I'm guessing the second one's meant to link to here: https://www.instagram.com/lischi_art/
I couldn't find a relevant Figma page using Google.

**Comment by FlorianKoerner** [comment]
Thank you. I have fixed it on the website.
