### ISSUE TITLE
Initials with white background

### ISSUE THREAD

**Issue by zaenkhilji** [dicebear/dicebear#256]
The text on initials with white background  is staying white, meaning invisible

`https://avatars.dicebear.com/api/initials/HelloWorld.svg?backgroundColor=WHITE`

**Comment by FlorianKoerner** [comment]
In the next version Minor the font color can be customized. Thanks for your suggestion!

**Comment by FlorianKoerner** [comment]
https://github.com/dicebear/dicebear/discussions/261
