### ISSUE TITLE
Support gradients as background

### ISSUE THREAD

**Issue by FlorianKoerner** [dicebear/dicebear#260]

**Comment by tslater** [comment]
@FlorianKoerner I'm using the figma plugin and all of the components generated with gradients just have white fills. Is there anything special I need to do to make sure they work?

**Comment by FlorianKoerner** [comment]
@tslater Two possible sources of error come to mind:

- Does your frame in Figma have a white background color? The frame must be transparent.
- Have you perhaps forgotten to define background colors?

To be able to help you more specifically, I need the Figma file and the options you use to create the avatars.

You can send me both via e-mail to contact@dicebear.com.

**Comment by tslater** [comment]
@FlorianKoerner I realize now that I misspoke. The issue was being able to use gradients for the avatar's body. Hopefully that is supported as well? I sent you an email with a link to our Figma file. Thanks so much!

**Comment by FlorianKoerner** [comment]
Hi @tslater thanks for the mail. I have replied to you by e-mail. Let me know if it hasn't arrived. In your case there is a workaround.
