### ISSUE TITLE
Can't host the API without docker

### ISSUE THREAD

**Issue by Marti-SV** [dicebear/dicebear#272]
Hello, I'm studing web developent and when I am trying to create a project with your API to make te avatars of the website but I'm having problems hosting it myself.

I tried to do the same steps as the [manual](url):

_git clone https://github.com/dicebear/api.git_
![image](https://user-images.githubusercontent.com/113421500/217105775-bf110560-de2c-4721-9dea-c502d8fb316a.png)

_cd api_
![image](https://user-images.githubusercontent.com/113421500/217105787-08dd708c-2c3c-495c-98a6-83cb9fa95798.png)

_npm install_
![image](https://user-images.githubusercontent.com/113421500/217105805-84744099-3898-45ba-a111-99059d178f68.png)
![image](https://user-images.githubusercontent.com/113421500/217105830-46908499-f976-4b9f-86ac-1462e85c07fd.png)

_npm start_
![image](https://user-images.githubusercontent.com/113421500/217104895-359e1d9a-ee8d-4567-bf43-61fe41ece51a.png)

And it dosen't run, just stays like charging something :P

**Comment by FlorianKoerner** [comment]
That's all the console outputs at this point. A success message is definitely still missing here.

Just go to http://localhost:3000. It should work.

**Comment by Marti-SV** [comment]
We just checked localhost and it's working, thank you Florian! Have a nice day :)
