### ISSUE TITLE
avataaars 'topProbability'

### ISSUE THREAD

**Issue by Bippitee** [dicebear/dicebear#274]
I understand this is very much a me issue, but just putting it out there, as a bald man with a beard. 😂 

When setting topProbability to 0 - i.e. making a baldie, it seems to also set facialHairProbability and accessoriesProbability to 0 as well. 
Alternatively, while the avataaars-generator is out of date, there's a "NoHair" option that allows no hair & accessories/facial hair. 

Also shouldn't 'beardMagestic' be beardMajestic? 

Love your work!

**Comment by FlorianKoerner** [comment]
Hi @Bippitee

You are right. 👍  I will look at this in detail.

**Comment by FlorianKoerner** [comment]
Fixed
https://github.com/dicebear/dicebear/releases/tag/v6.0.0

**Comment by i-am-the-slime** [comment]
Is it a joke that it says M**e**jestic in the Release Notes?

**Comment by FlorianKoerner** [comment]
> Is it a joke that it says M**e**jestic in the Release Notes?

Just a (repeated) typo in the changelogs. I shouldn't write the changelogs so late in the evening. 🥱😂 I have corrected it.
