### ISSUE TITLE
Initials not working for PNG format

### ISSUE THREAD

**Issue by karelric** [dicebear/dicebear#281]
When sending `https://api.dicebear.com/5.x/initials/png?seed=JohnDoe` is returning an empty picture with random background although.

**Comment by FlorianKoerner** [comment]
Hi @karelric - Thank you for reporting.

This is a bug in the new version of the `@resvg/resvg-js` package. I have downgraded the package and created an issue.
https://github.com/yisibl/resvg-js/issues/207

![](https://api.dicebear.com/5.x/initials/png?seed=JohnDoe)
