### ISSUE TITLE
Setting style to ['circle'] for avataaars causes the avatar to be invisible in React Native

### ISSUE THREAD

**Issue by eeshankeni** [dicebear/dicebear#287]
I've noticed that this problem has been happening after migrating from 4.0. Thanks!

https://github.com/eeshankeni/dicebeartest

![without circle](https://user-images.githubusercontent.com/19875557/221374297-0882f136-5319-4178-81ad-2893a0edcc6c.jpg)
![with circle](https://user-images.githubusercontent.com/19875557/221374299-4908494d-ac21-4c01-9316-f61857edf005.jpg)

**Comment by FlorianKoerner** [comment]
Fixed
https://github.com/dicebear/dicebear/releases/tag/v6.0.0
