### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by QazCetelic** [dicebear/dicebear#290]
I'm unable to securely connect with [dicebear.com](https://dicebear.com). The server points to `2001-08d8-100f-f000-0000-0000-0000-0200.elastic-ssl.ui-r.com`.

![firefox_connection_info](https://user-images.githubusercontent.com/51381523/222514849-2bbf2c22-a2f9-414d-a6ae-2b62087304d2.png)

I first experienced this issue at 17:23 CET (16:23 UTC).

**Comment by FlorianKoerner** [comment]
This was caused by a DNS misconfiguration due to a provider change. Should work again.
