### ISSUE TITLE
Add `gender` option

### ISSUE THREAD

**Issue by AntwanSherif** [dicebear/dicebear#291]
Hello guys,
I'm really loving your work, keep it up 👏🏻

I'm currently creating a platform where I want to generate anonymous username and avatar for users (example: username is "hungrycat" and avatar will be "https://avatars.dicebear.com/api/micah/hungrycat.svg").

The problem is that the generated image depends on the used text ("hungrycat" in our case) and there's no way to determine the gender of the generated images.

Can you add an option to specify gender?

**Comment by FlorianKoerner** [comment]
Hi, there is no direct option for this. But you can mix the options to create an avatar that you think looks female or male.

- https://github.com/dicebear/dicebear/issues/247
- https://github.com/dicebear/dicebear/issues/21
- https://github.com/dicebear/dicebear/issues/180
- https://github.com/dicebear/dicebear/issues/100
