### ISSUE TITLE
Provide a Comprehensive Dictionary of Available Options for Each Style (Enhance Documentation)

### ISSUE THREAD

**Issue by 3aluw** [dicebear/dicebear#341]
Hello,
Currently, users of the CLI or API are required to explore the style's documentation to discover all available options, as accessing them  [programmatically ](https://www.dicebear.com/guides/access-all-available-options#how-to-programmatically-access-all-available-options-of-an-avatar-style) involves installing the library.
This process can be overwhelming, as users need to scroll and search for specific options and their accepted values. For instance, navigating the [open-peeps documentation](https://www.dicebear.com/styles/open-peeps) can be quite daunting.

I propose a solution to improve the user experience by incorporating a comprehensive dictionary (table) of all available options and their types at the top of every styles' documentation with a button that allows the user to conveniently download the information as a JSON file, achieving an easier reference and usage.

Thank you.

**Comment by FlorianKoerner** [comment]
JSON-File without installing JS-Library:
https://github.com/orgs/dicebear/discussions/337

**Comment by 3aluw** [comment]
@FlorianKoerner that's cool, The link should be added to the documentation of each style.

**Comment by FlorianKoerner** [comment]
https://github.com/dicebear/dicebear/releases/tag/v7.0.0
