### ISSUE TITLE
Add a LICENSE file repository

### ISSUE THREAD

**Issue by MokuluaDev** [dicebear/dicebear#354]
This repo is missing a LICENSE file. According to the [DiceBear website](https://www.dicebear.com/licenses), it would appear this code should be MIT licensed like the rest. Could you please add a LICENSE file to this repository, as well?

**Comment by FlorianKoerner** [comment]
The licenses are located in the folders of the packages: https://github.com/dicebear/dicebear/tree/main/packages/%40dicebear

@dicebear/core: https://github.com/dicebear/dicebear/blob/main/packages/%40dicebear/core/LICENSE
