### ISSUE TITLE
createAvatar() doesn't generate JSON

### ISSUE THREAD

**Issue by weronikazak** [dicebear/dicebear#355]
Hey! I have a similar issue as #259. However, in my case, the `createAvatar()` function returns just the SVG format without other props. Any idea on how to fix it?
Great library btw, keep up the great work! :)

**Comment by FlorianKoerner** [comment]
The example was wrong. This should work:

```js
import { createAvatar } from '@dicebear/core';
import { initials } from '@dicebear/collection';

const avatar = createAvatar(initials, {
  seed: 'John Doe'
});

const svg = avatar.toJson();
```
