### ISSUE TITLE
`eyeShadowColor` for micah doesn't work

### ISSUE THREAD

**Issue by weronikazak** [dicebear/dicebear#356]
Hello! I've noticed that setting eyeshadow color for Micah doesn't seem to work.
Example with expected pink eyeshadow: https://api.dicebear.com/7.x/micah/svg?eyeShadowColor=f030b9
<image src="https://api.dicebear.com/7.x/micah/svg?eyeShadowColor=f030b9" width=200 heigh=200/>

**Comment by FlorianKoerner** [comment]
Fixed :)
