### ISSUE TITLE
error when running npm run test

### ISSUE THREAD

**Issue by pierroo** [dicebear/dicebear#369]
I have followed the figma documentation:
https://www.dicebear.com/guides/create-an-avatar-style-with-figma

I got my zip with expected files;
I have npm install, then npm run build, no issue

But when I run npm run test I get the following error:

![image](https://github.com/dicebear/dicebear/assets/17619412/4390261f-dbee-46b0-ae82-dca2d9f67bf8)

I even tried to create the tests/static/create folder just in case, but same error

I console.log the svgPath to make sure, and it's giving:
C:\C:\dev\avatar_test\tests\static\create\0.svg
I guess the issue lies in the double C:/C:/
but I have no clue why it happens?

Edit: I manually entered the correct path, and now the test script is running as expected.
So the issue seems to lie in the **path.resolve**(__dirname, 'static/create', `${key}.svg`)
I don't mean to pollute this repo, feel free to close it if it's unrelated; but somehow it may help others?

**Comment by FlorianKoerner** [comment]
Hi @pierroo . The script was not tested on Windows. Thanks for the tip. I will take a look at it.
