### ISSUE TITLE
Are the extended top options included?

### ISSUE THREAD

**Issue by rachisalive** [dicebear/dicebear#74]
In the [avataaars ]( https://getavataaars.com ) generator, options like 
`topType=LongHairDreads` exists. Do these extended options exist within this api? If so, how would I define them...?

```javascript
let options = {
  top: ['LongHairDreads']
};
let avatars = new Avatars(sprites, options );
let svg = avatars.create('example-seed');
```

**Comment by FlorianKoerner** [comment]
Which options are available to you, you can read in this README:
https://github.com/DiceBear/avatars/tree/master/packages/avatars-avataaars-sprites#options

For "top" you can choose among the following: longHair, shortHair, eyepatch, hat, hijab, turban
With the upcoming version 5.0 more values will be available.

Does that answer your question?

**Comment by jordanorc** [comment]
@FlorianKoerner, thank you for your excellent work. There is any plan to make more options available or when v5 will be available?

**Comment by FlorianKoerner** [comment]
Version 5 is still under development. It will be released in the course of the year. I will check again if we can already include this with the current version.

**Comment by jordanorc** [comment]
@FlorianKoerner, let me know if I can help with this.

**Comment by FlorianKoerner** [comment]
First release candidate has just been published. Can be installed with:

```
npm i @dicebear/avatars@next @dicebear/avatars-avataaars-sprites@next
```

Stable release will follow on sunday, when API and documentation have been updated.

**Comment by FlorianKoerner** [comment]
Released. See: https://avatars.dicebear.com/styles/avataaars#style-options

**Comment by jordanorc** [comment]
@FlorianKoerner, thanks. I will try it. Great work!
