### ISSUE TITLE
Support micah

### ISSUE THREAD

**Issue by FlorianKoerner** [dicebear/dicebear#88]
https://www.figma.com/community/file/829741575478342595

**Comment by whiteyhat** [comment]
is this happening any time soon?

**Comment by FlorianKoerner** [comment]
In the next two weeks.

**Comment by whiteyhat** [comment]
Looking forward to this @FlorianKoerner

**Comment by FlorianKoerner** [comment]
First release candidate has just been published. Can be installed with:

```
npm i @dicebear/avatars@next @dicebear/micah@next
```

Stable release will follow on sunday, when API and documentation have been updated.

**Comment by FlorianKoerner** [comment]
Released. See: https://avatars.dicebear.com/styles/micah
